version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: rentdrivewebapp-nginx-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    image: rentdrivewebapp-frontend
    container_name: rentdrivewebapp-frontend-1
    networks:
      - app-network

  backend:
    image: rentdrivewebapp-backend
    container_name: rentdrivewebapp-backend-1
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: rentdrivewebapp-certbot-1
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: rentdrivewebapp-db-1
    environment:
      POSTGRES_PASSWORD: yourpassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
