services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: rentdrive
      POSTGRES_USER: rentdrive
      POSTGRES_PASSWORD: rentdrive2025
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: RentDrive.Backend/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rentdrive
      DB_USER: rentdrive
      DB_PASS: rentdrive2025
      ASPNETCORE_ENVIRONMENT: Production
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    build: ./RentDrive.Frontend
    depends_on:
      - backend
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
  db_data:
  certbot-etc:
  certbot-var:
