services:
  nginx:
    image: nginx:stable
    container_name: rentdrivewebapp-nginx-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - images-data:/usr/share/nginx/html/images:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    image: viktor9904/rentdrivewebapp-frontend:latest
    container_name: rentdrivewebapp-frontend-1
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: viktor9904/rentdrivewebapp-backend:latest
    volumes:
      - images-data:/app/wwwroot/images
    container_name: rentdrivewebapp-backend-1
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rentdrive
      DB_USER: rentdrive
      DB_PASS: rentdrive
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      db:
        condition: service_healthy

  certbot:
    image: certbot/certbot
    container_name: rentdrivewebapp-certbot-1
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: rentdrivewebapp-db-1
    environment:
      POSTGRES_DB: rentdrive
      POSTGRES_USER: rentdrive
      POSTGRES_PASSWORD: rentdrive
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  images-data:
  db-data: