services:
  frontend:
    image: rentdrivewebapp-frontend
    container_name: frontend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: rentdrivewebapp-backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
