// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentDrive.Data;

#nullable disable

namespace RentDrive.Data.Migrations
{
    [DbContext(typeof(RentDriveDbContext))]
    [Migration("20250626130534_AddedEngineDisplacementAndPowerInKiloWattsToMotorcycle")]
    partial class AddedEngineDisplacementAndPowerInKiloWattsToMotorcycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RentDrive.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("User profile creation time (UTC).");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompanyEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Is the user employee of the company.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RentDrive.Data.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Vehicle's color.");

                    b.Property<double>("CurbWeightInKg")
                        .HasColumnType("float")
                        .HasComment("Weight of the vehicle when empty in kilograms.");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfProduction")
                        .HasColumnType("datetime2")
                        .HasComment("Vehicle's manufactured date.");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Optional description of the vehicle.");

                    b.Property<int>("FuelType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Vehicle fuel type.");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Manufacturer of the vehicle.");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Model of the vehicle.");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The owner's Id of the vehicle. Null if the vehicle is company-owned.");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price per day for renting the vehicle.");

                    b.Property<int>("VehicleTypeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("VehicleTypeCategoryId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            Color = "White",
                            CurbWeightInKg = 1470.0,
                            DateAdded = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfProduction = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable midsize sedan, ideal for long drives.",
                            FuelType = 1,
                            Make = "Toyota",
                            Model = "Camry",
                            PricePerDay = 32.50m,
                            VehicleTypeCategoryId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            Color = "Dark Green",
                            CurbWeightInKg = 2045.0,
                            DateAdded = new DateTime(2023, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfProduction = new DateTime(2022, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spacious and off-road capable SUV.",
                            FuelType = 2,
                            Make = "Jeep",
                            Model = "Grand Cherokee",
                            PricePerDay = 62.00m,
                            VehicleTypeCategoryId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            Color = "Silver",
                            CurbWeightInKg = 1300.0,
                            DateAdded = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfProduction = new DateTime(2021, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact hatchback with great fuel economy.",
                            FuelType = 1,
                            Make = "Volkswagen",
                            Model = "Golf",
                            PricePerDay = 54.00m,
                            VehicleTypeCategoryId = 3,
                            VehicleTypeId = 1
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasDefaultValue("images/default-image.jpg")
                        .HasComment("Vehicle Image URL.");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a35616f3-67b2-4d66-95cd-78fae80883fa"),
                            ImageURL = "/images/vehicles/Vehicle-1.png",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de")
                        },
                        new
                        {
                            Id = new Guid("47725763-dc3a-485b-9f12-26df29497dd1"),
                            ImageURL = "/images/vehicles/Vehicle-3.jpg",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743")
                        },
                        new
                        {
                            Id = new Guid("1d989d71-afdb-4741-8851-dedc44ffe964"),
                            ImageURL = "/images/vehicles/Vehicle-2.jpg",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4")
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the vehicle type.");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Truck"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Motorcycle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bicycle"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Electric Scooter"
                        },
                        new
                        {
                            Id = 6,
                            Name = "All Terrain Vehicle (ATV)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Camper Trailer"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Recreational Vehicle"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Limousine"
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Description of the vehicle class.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the vehicle class.");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId", "Name")
                        .IsUnique();

                    b.ToTable("VehicleTypeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spacious and powerful car ideal for families and off-road.",
                            Name = "SUV",
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comfortable passenger car suitable for everyday use.",
                            Name = "Sedan",
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compact car with a rear door that swings upward.",
                            Name = "Hatchback",
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Truck with an open cargo area in the back.",
                            Name = "Pickup",
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Truck with a large, enclosed cargo area.",
                            Name = "Box Truck",
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Very good bike for everyday riding.",
                            Name = "Naked",
                            VehicleTypeId = 3
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Property Name");

                    b.Property<int>("UnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Property unit of measurement");

                    b.Property<int>("ValueType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Property value type");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleTypeProperties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25"),
                            Name = "Engine Displacement",
                            UnitOfMeasurement = 5,
                            ValueType = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d"),
                            Name = "Door Count",
                            UnitOfMeasurement = 0,
                            ValueType = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db"),
                            Name = "Seat Count",
                            UnitOfMeasurement = 0,
                            ValueType = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f"),
                            Name = "Power in KiloWatts",
                            UnitOfMeasurement = 8,
                            ValueType = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("b924497e-006a-4d20-899f-66fde6c94ec8"),
                            Name = "Engine Displacement",
                            UnitOfMeasurement = 5,
                            ValueType = 1,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = new Guid("6b197695-891b-492a-8935-a54a500742c2"),
                            Name = "Power in KiloWatts",
                            UnitOfMeasurement = 8,
                            ValueType = 2,
                            VehicleTypeId = 3
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypePropertyValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Property Value");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleTypePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypePropertyId");

                    b.HasIndex("VehicleId", "VehicleTypePropertyId")
                        .IsUnique();

                    b.ToTable("VehicleTypePropertyValues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4bdc05a2-559f-412c-994a-69c1ac6ab24f"),
                            PropertyValue = "2487",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25")
                        },
                        new
                        {
                            Id = new Guid("53c60eee-041b-4cf7-828f-43c0c3000305"),
                            PropertyValue = "4",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d")
                        },
                        new
                        {
                            Id = new Guid("c9951dc1-d840-42b4-854e-44104883613f"),
                            PropertyValue = "5",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db")
                        },
                        new
                        {
                            Id = new Guid("e0c89c2c-28ad-496d-bee9-17da515dee11"),
                            PropertyValue = "151",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f")
                        },
                        new
                        {
                            Id = new Guid("92820a2c-2324-4279-aff9-8e606f868200"),
                            PropertyValue = "3604",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25")
                        },
                        new
                        {
                            Id = new Guid("ea03bee5-44ac-4140-90e4-5932694920b7"),
                            PropertyValue = "4",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d")
                        },
                        new
                        {
                            Id = new Guid("838bb66e-a194-4b05-a35d-397746dbc375"),
                            PropertyValue = "7",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db")
                        },
                        new
                        {
                            Id = new Guid("43049eae-e00f-48c0-94a1-dbcd66f1b892"),
                            PropertyValue = "218",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f")
                        },
                        new
                        {
                            Id = new Guid("dfd548e3-0542-435e-b80e-b349a0e86c79"),
                            PropertyValue = "1395",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25")
                        },
                        new
                        {
                            Id = new Guid("226d11c2-6ace-482d-8c05-052ae6a36df5"),
                            PropertyValue = "5",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d")
                        },
                        new
                        {
                            Id = new Guid("e400d83c-9533-426f-b6ce-5916ce24f510"),
                            PropertyValue = "5",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db")
                        },
                        new
                        {
                            Id = new Guid("deb2022f-58a6-46de-93de-78266eb453b2"),
                            PropertyValue = "110",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentDrive.Data.Models.Vehicle", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RentDrive.Data.Models.VehicleTypeCategory", "VehicleTypeCategory")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("VehicleType");

                    b.Navigation("VehicleTypeCategory");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleImages", b =>
                {
                    b.HasOne("RentDrive.Data.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeCategory", b =>
                {
                    b.HasOne("RentDrive.Data.Models.VehicleType", "VehicleType")
                        .WithMany("VehicleTypeCategory")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeProperty", b =>
                {
                    b.HasOne("RentDrive.Data.Models.VehicleType", "VehicleType")
                        .WithMany("VehicleTypeProperty")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypePropertyValue", b =>
                {
                    b.HasOne("RentDrive.Data.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleTypePropertyValues")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.VehicleTypeProperty", "VehicleTypeProperty")
                        .WithMany("VehicleTypePropertyValues")
                        .HasForeignKey("VehicleTypePropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleTypeProperty");
                });

            modelBuilder.Entity("RentDrive.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RentDrive.Data.Models.Vehicle", b =>
                {
                    b.Navigation("VehicleImages");

                    b.Navigation("VehicleTypePropertyValues");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleType", b =>
                {
                    b.Navigation("VehicleTypeCategory");

                    b.Navigation("VehicleTypeProperty");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeCategory", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeProperty", b =>
                {
                    b.Navigation("VehicleTypePropertyValues");
                });
#pragma warning restore 612, 618
        }
    }
}
