// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentDrive.Data;

#nullable disable

namespace RentDrive.Data.Migrations
{
    [DbContext(typeof(RentDriveDbContext))]
    [Migration("20250730111449_AddedVehicleReviewSeeder")]
    partial class AddedVehicleReviewSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RentDrive.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("User profile creation time (UTC).");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompanyEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Is the user employee of the company.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RentDrive.Data.Models.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of booking.");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of cancelled rental.");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Rental date of completion.");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("End day of rental.");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Start day of rental.");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Status of rental");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total price for renting.");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VehiclePricePerDay")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Vehicle price per day.");

                    b.HasKey("Id");

                    b.HasIndex("RenterId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a25e78-2b30-4f77-a899-08db1682a00a"),
                            BookedOn = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CompletedOn = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            StartDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 130.00m,
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehiclePricePerDay = 32.50m
                        },
                        new
                        {
                            Id = new Guid("9cfe3db6-50e1-41e4-8a98-3cdba63c20b1"),
                            BookedOn = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("e7df3bc2-1c20-4895-b8c9-781ad6cf892a"),
                            StartDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalPrice = 162.50m,
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehiclePricePerDay = 32.50m
                        },
                        new
                        {
                            Id = new Guid("7bb21c7b-d0d8-4de0-8d84-2e8d4bffec85"),
                            BookedOn = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("e7df3bc2-1c20-4895-b8c9-781ad6cf892a"),
                            StartDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalPrice = 162.50m,
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehiclePricePerDay = 32.50m
                        },
                        new
                        {
                            Id = new Guid("b2c98c1a-45f4-4b89-9a74-51cfa684b9e2"),
                            BookedOn = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CompletedOn = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            StartDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 372.00m,
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehiclePricePerDay = 62.00m
                        },
                        new
                        {
                            Id = new Guid("a5f61b5a-883e-47f4-8189-44b197967d5f"),
                            BookedOn = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("e7df3bc2-1c20-4895-b8c9-781ad6cf892a"),
                            StartDate = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalPrice = 310.00m,
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehiclePricePerDay = 62.00m
                        },
                        new
                        {
                            Id = new Guid("f62e7790-609b-4a42-a01c-fbb6d8c88f89"),
                            BookedOn = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalPrice = 310.00m,
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehiclePricePerDay = 62.00m
                        },
                        new
                        {
                            Id = new Guid("dca1c233-b01b-4f6c-a0fc-f6b709bd92ef"),
                            BookedOn = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CompletedOn = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("e7df3bc2-1c20-4895-b8c9-781ad6cf892a"),
                            StartDate = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalPrice = 270.00m,
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehiclePricePerDay = 54.00m
                        },
                        new
                        {
                            Id = new Guid("c63cc240-39c6-4d55-b5cf-bd17912825fc"),
                            BookedOn = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            StartDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalPrice = 270.00m,
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehiclePricePerDay = 54.00m
                        },
                        new
                        {
                            Id = new Guid("f471e13c-5fae-4421-9fa4-300b08b97c28"),
                            BookedOn = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenterId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            StartDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalPrice = 270.00m,
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehiclePricePerDay = 54.00m
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Vehicle's color.");

                    b.Property<double>("CurbWeightInKg")
                        .HasColumnType("float")
                        .HasComment("Weight of the vehicle when empty in kilograms.");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfProduction")
                        .HasColumnType("datetime2")
                        .HasComment("Vehicle's manufactured date.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Optional description of the vehicle.");

                    b.Property<int>("FuelType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Vehicle fuel type.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the vehicle is soft deleted.");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Manufacturer of the vehicle.");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Model of the vehicle.");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The owner's Id of the vehicle. Null if the vehicle is company-owned.");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price per day for renting the vehicle.");

                    b.Property<int>("VehicleTypeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("VehicleTypeCategoryId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            Color = "White",
                            CurbWeightInKg = 1470.0,
                            DateAdded = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfProduction = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable midsize sedan, ideal for long drives.",
                            FuelType = 1,
                            IsDeleted = false,
                            Make = "Toyota",
                            Model = "Camry",
                            PricePerDay = 32.50m,
                            VehicleTypeCategoryId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            Color = "Dark Green",
                            CurbWeightInKg = 2045.0,
                            DateAdded = new DateTime(2023, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfProduction = new DateTime(2022, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spacious and off-road capable SUV.",
                            FuelType = 2,
                            IsDeleted = false,
                            Make = "Jeep",
                            Model = "Grand Cherokee",
                            PricePerDay = 62.00m,
                            VehicleTypeCategoryId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            Color = "Silver",
                            CurbWeightInKg = 1300.0,
                            DateAdded = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfProduction = new DateTime(2021, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact hatchback with great fuel economy.",
                            FuelType = 1,
                            IsDeleted = false,
                            Make = "Volkswagen",
                            Model = "Golf",
                            PricePerDay = 54.00m,
                            VehicleTypeCategoryId = 3,
                            VehicleTypeId = 1
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasDefaultValue("images/default-image.jpg")
                        .HasComment("Vehicle Image URL.");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a35616f3-67b2-4d66-95cd-78fae80883fa"),
                            ImageURL = "images/vehicles/Vehicle-1.png",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de")
                        },
                        new
                        {
                            Id = new Guid("47725763-dc3a-485b-9f12-26df29497dd1"),
                            ImageURL = "images/vehicles/Vehicle-3.jpg",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743")
                        },
                        new
                        {
                            Id = new Guid("1d989d71-afdb-4741-8851-dedc44ffe964"),
                            ImageURL = "images/vehicles/Vehicle-2.jpg",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4")
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Review Comment");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Review creation date.");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasComment("Vehicle rating scale from 0 to 10.");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.HasIndex("ReviewerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleReviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Comment = "Smooth ride, very clean, great experience!",
                            CreatedOn = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalId = new Guid("a1a25e78-2b30-4f77-a899-08db1682a00a"),
                            ReviewerId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            Stars = 5,
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de")
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Comment = "Engine was louder than expected, not well maintained.",
                            CreatedOn = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalId = new Guid("9cfe3db6-50e1-41e4-8a98-3cdba63c20b1"),
                            ReviewerId = new Guid("e7df3bc2-1c20-4895-b8c9-781ad6cf892a"),
                            Stars = 2,
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            Comment = "Powerful SUV, great for the mountains.",
                            CreatedOn = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalId = new Guid("b2c98c1a-45f4-4b89-9a74-51cfa684b9e2"),
                            ReviewerId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            Stars = 4,
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743")
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-dddddddddddd"),
                            Comment = "Uncomfortable seats and poor air conditioning.",
                            CreatedOn = new DateTime(2025, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalId = new Guid("a5f61b5a-883e-47f4-8189-44b197967d5f"),
                            ReviewerId = new Guid("e7df3bc2-1c20-4895-b8c9-781ad6cf892a"),
                            Stars = 1,
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743")
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Comment = "Decent for city driving, but not spacious.",
                            CreatedOn = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalId = new Guid("dca1c233-b01b-4f6c-a0fc-f6b709bd92ef"),
                            ReviewerId = new Guid("e7df3bc2-1c20-4895-b8c9-781ad6cf892a"),
                            Stars = 3,
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4")
                        },
                        new
                        {
                            Id = new Guid("66666666-ffff-ffff-ffff-ffffffffffff"),
                            Comment = "Very fuel efficient and easy to park!",
                            CreatedOn = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalId = new Guid("c63cc240-39c6-4d55-b5cf-bd17912825fc"),
                            ReviewerId = new Guid("d56b4e71-7c38-4c3f-8c85-ff2b7cfd2f01"),
                            Stars = 5,
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4")
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Is vehicle type soft deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the vehicle type.");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Truck"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Motorcycle"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Bicycle"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Electric Scooter"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "All Terrain Vehicle (ATV)"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Camper Trailer"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Recreational Vehicle"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Limousine"
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Description of the vehicle class.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Is vehicle type category soft deleted.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the vehicle class.");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId", "Name")
                        .IsUnique();

                    b.ToTable("VehicleTypeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spacious and powerful car ideal for families and off-road.",
                            IsDeleted = false,
                            Name = "SUV",
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comfortable passenger car suitable for everyday use.",
                            IsDeleted = false,
                            Name = "Sedan",
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compact car with a rear door that swings upward.",
                            IsDeleted = false,
                            Name = "Hatchback",
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Truck with an open cargo area in the back.",
                            IsDeleted = false,
                            Name = "Pickup",
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Truck with a large, enclosed cargo area.",
                            IsDeleted = false,
                            Name = "Box Truck",
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Very good bike for everyday riding.",
                            IsDeleted = false,
                            Name = "Naked",
                            VehicleTypeId = 3
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Property Name");

                    b.Property<int>("UnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Property unit of measurement");

                    b.Property<int>("ValueType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Property value type");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleTypeProperties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25"),
                            Name = "Engine Displacement",
                            UnitOfMeasurement = 5,
                            ValueType = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d"),
                            Name = "Door Count",
                            UnitOfMeasurement = 0,
                            ValueType = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db"),
                            Name = "Seat Count",
                            UnitOfMeasurement = 0,
                            ValueType = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f"),
                            Name = "Power in KiloWatts",
                            UnitOfMeasurement = 8,
                            ValueType = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("b924497e-006a-4d20-899f-66fde6c94ec8"),
                            Name = "Engine Displacement",
                            UnitOfMeasurement = 5,
                            ValueType = 1,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = new Guid("6b197695-891b-492a-8935-a54a500742c2"),
                            Name = "Power in KiloWatts",
                            UnitOfMeasurement = 8,
                            ValueType = 2,
                            VehicleTypeId = 3
                        });
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypePropertyValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Property Value");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleTypePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypePropertyId");

                    b.HasIndex("VehicleId", "VehicleTypePropertyId")
                        .IsUnique();

                    b.ToTable("VehicleTypePropertyValues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4bdc05a2-559f-412c-994a-69c1ac6ab24f"),
                            PropertyValue = "2487",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25")
                        },
                        new
                        {
                            Id = new Guid("53c60eee-041b-4cf7-828f-43c0c3000305"),
                            PropertyValue = "4",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d")
                        },
                        new
                        {
                            Id = new Guid("c9951dc1-d840-42b4-854e-44104883613f"),
                            PropertyValue = "5",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db")
                        },
                        new
                        {
                            Id = new Guid("e0c89c2c-28ad-496d-bee9-17da515dee11"),
                            PropertyValue = "151",
                            VehicleId = new Guid("6a8e2d12-04a3-4c55-8b2b-f9a0f1fd35de"),
                            VehicleTypePropertyId = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f")
                        },
                        new
                        {
                            Id = new Guid("92820a2c-2324-4279-aff9-8e606f868200"),
                            PropertyValue = "3604",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25")
                        },
                        new
                        {
                            Id = new Guid("ea03bee5-44ac-4140-90e4-5932694920b7"),
                            PropertyValue = "4",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d")
                        },
                        new
                        {
                            Id = new Guid("838bb66e-a194-4b05-a35d-397746dbc375"),
                            PropertyValue = "7",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db")
                        },
                        new
                        {
                            Id = new Guid("43049eae-e00f-48c0-94a1-dbcd66f1b892"),
                            PropertyValue = "218",
                            VehicleId = new Guid("fe15cde2-1a90-46d4-89f1-10fda7f11743"),
                            VehicleTypePropertyId = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f")
                        },
                        new
                        {
                            Id = new Guid("dfd548e3-0542-435e-b80e-b349a0e86c79"),
                            PropertyValue = "1395",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("671fbc1d-53ef-4862-9f73-974b94ac0d25")
                        },
                        new
                        {
                            Id = new Guid("226d11c2-6ace-482d-8c05-052ae6a36df5"),
                            PropertyValue = "5",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("13aaad5c-624c-4361-a863-6ff301f5c63d")
                        },
                        new
                        {
                            Id = new Guid("e400d83c-9533-426f-b6ce-5916ce24f510"),
                            PropertyValue = "5",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("77ab0d68-a40a-413a-9b4a-aa30716609db")
                        },
                        new
                        {
                            Id = new Guid("deb2022f-58a6-46de-93de-78266eb453b2"),
                            PropertyValue = "110",
                            VehicleId = new Guid("ff71fcbc-6829-47fd-81c7-d16d7c2c34b4"),
                            VehicleTypePropertyId = new Guid("dd348516-a1dc-4336-b6c8-fb885b7afd0f")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentDrive.Data.Models.Rental", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", "Renter")
                        .WithMany("Rentals")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RentDrive.Data.Models.Vehicle", b =>
                {
                    b.HasOne("RentDrive.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RentDrive.Data.Models.VehicleTypeCategory", "VehicleTypeCategory")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("VehicleType");

                    b.Navigation("VehicleTypeCategory");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleImage", b =>
                {
                    b.HasOne("RentDrive.Data.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleReview", b =>
                {
                    b.HasOne("RentDrive.Data.Models.Rental", "Rental")
                        .WithOne("Review")
                        .HasForeignKey("RentDrive.Data.Models.VehicleReview", "RentalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.ApplicationUser", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.Vehicle", "Vehicle")
                        .WithMany("Reviews")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rental");

                    b.Navigation("Reviewer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeCategory", b =>
                {
                    b.HasOne("RentDrive.Data.Models.VehicleType", "VehicleType")
                        .WithMany("VehicleTypeCategory")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeProperty", b =>
                {
                    b.HasOne("RentDrive.Data.Models.VehicleType", "VehicleType")
                        .WithMany("VehicleTypeProperty")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypePropertyValue", b =>
                {
                    b.HasOne("RentDrive.Data.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleTypePropertyValues")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentDrive.Data.Models.VehicleTypeProperty", "VehicleTypeProperty")
                        .WithMany("VehicleTypePropertyValues")
                        .HasForeignKey("VehicleTypePropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleTypeProperty");
                });

            modelBuilder.Entity("RentDrive.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RentDrive.Data.Models.Rental", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("RentDrive.Data.Models.Vehicle", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Reviews");

                    b.Navigation("VehicleImages");

                    b.Navigation("VehicleTypePropertyValues");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleType", b =>
                {
                    b.Navigation("VehicleTypeCategory");

                    b.Navigation("VehicleTypeProperty");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeCategory", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RentDrive.Data.Models.VehicleTypeProperty", b =>
                {
                    b.Navigation("VehicleTypePropertyValues");
                });
#pragma warning restore 612, 618
        }
    }
}
