name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: RentDrive.Backend/Dockerfile
          push: true
          tags: viktor9904/rentdrivewebapp-backend:latest
          platforms: linux/arm64
          build-args: |
            ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./RentDrive.Frontend
          push: true
          tags: viktor9904/rentdrivewebapp-frontend:latest
          platforms: linux/arm64